name: Basic CI

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: DangerSwiftLint
        run: |
          brew install danger/tap/danger-swift
          export DANGER_GITHUB_API_TOKEN='${{ secrets.GH_TOKEN }}'
          danger-swift ci

      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: Example/Podfile.lock

      - name: Lint pod library
        working-directory: Example
        run: pod lib lint --skip-tests

#  test:
#    runs-on: macos-latest
#
#    steps:
#      - uses: actions/checkout@v3
