name: Build

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: DangerSwiftLint
        run: |
          brew install danger/tap/danger-swift
          export DANGER_GITHUB_API_TOKEN='${{ secrets.GH_TOKEN }}'
          danger-swift ci

      - name: Lint pod library
        run: pod lib lint --skip-tests
